version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: workshopdb
    volumes:
      - workshop-volume:/var/lib/postgresql/data

  workshop-main:
    container_name: workshop-main
    image: stempz/workshop:1.0.0
    ports:
      - '8080:8080'
    environment:
      DB_URL: jdbc:postgresql://postgres/workshopdb
      DB_USER: user
      DB_PASSWORD: pass
    depends_on:
      - postgres

volumes:
  workshop-volume:
