spring:
  application:
    name: workshop
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/workshopdb}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
